### ISSUE TITLE
Fix helpstring for empty cmdline in py3k

### ISSUE THREAD

**Issue by kyleabeauchamp** [counsyl/stor#25]
Typing `stor` leads to a `TypeError` on python3.5 (log below); on py27 it catches any errors and displays a helpful message  ("stor: error: too few arguments").  Two possible solutions are:

1.  Fix the config parser (https://github.com/counsyl/stor/blob/master/stor/cli.py#L370) to somehow propagate the "too few arguments" behavior as before
2.  Manually catch the TypeError (e.g., here: https://github.com/counsyl/stor/blob/master/stor/cli.py#L383) and print a slightly different error

FWIW, I'm mildly curious what in py35 broke the argument counting behavior.

```bash
$ stor
Traceback (most recent call last):
  File "~/miniconda2/envs/ontpipe/bin/stor", line 11, in <module>
    sys.exit(main())
  File "~/miniconda2/envs/ontpipe/lib/python3.5/site-packages/stor/cli.py", line 426, in main
    results = process_args(args)
  File "~/miniconda2/envs/ontpipe/lib/python3.5/site-packages/stor/cli.py", line 386, in process_args
    return func(**func_kwargs)
TypeError: 'NoneType' object is not callable


$ python --version
Python 3.5.0 :: Continuum Analytics, Inc.
```

**Comment by kyleabeauchamp** [comment]
I have confirmed that this is fixed in #28
