### ISSUE TITLE
Attempting use gzip.GzipFile with an OBSFile will error on Python 2.X

### ISSUE THREAD

**Issue by jtratner** [counsyl/stor#42]
Problem is that GzipFile (for whatever reason) stores the file name in plain text, so that means you end up with a buffer with a buflist that looks like:

```
(str, '<gzip data>')
(unicode, u'myfile.txt')
(str, '<gzip data>')
```

and on concatenation of these objects, it attempts to do the unicode decode/encode dance and you end up with a unicode error.

I'm not 100% sure what to do in Python 2 vs. Python 3 - I think we should hack around this in the following way:

Reproducible example:

```
with stor.open('swift://AUTH_swft_test/myfile.txt', 'wb') as fp:
    with gzip.GzipFile(fileobj=fp, 'w') as gfp:
             gfp.write('abc')
```

will generate UnicodeDecodeError if you're on a very old Python 2.7.

```
Traceback (most recent call last):
  File "<console>", line 3, in <module>
  File "stor/obs.py", line 277, in __exit__
    self.close()
  File "stor/obs.py", line 329, in close
    self.flush()
  File "stor/obs.py", line 340, in flush
    self._path.write_object(self._buffer.getvalue(),
  File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

So either we get everybody to upgrade past the version of Python that has this error - https://bugs.python.org/issue13639 - fixed

OR

we help out and have `fp.name` return a `str` instead of `text`.

**Comment by jtratner** [comment]
we got on a newer python, not really worth chasing down this error
